from __future__ import annotations

from typing import Any, Dict

from fastapi import APIRouter, Request

from proxy_core.presenters import build_ps_models, build_tags_models, effective_capabilities, merged_model_info, now_iso
from proxy_core.state import ProxyState, guess_model_family
from proxy_core.request_utils import parse_request_json


def create_models_router(state: ProxyState, logger) -> APIRouter:
    router = APIRouter()

    @router.get("/v1/models")
    @router.get("/api/models")
    async def list_models() -> Dict[str, Any]:
        discovery_errors = await state.ensure_discoverable_models_loaded()
        if not state.model_registry and discovery_errors:
            state.raise_discovery_error(discovery_errors[0])
        return {
            "object": "list",
            "data": [
                {"id": name, "object": "model", "created": 0, "owned_by": "proxy", "root": name}
                for name in state.model_registry.keys()
            ],
        }

    @router.get("/v1/models/{model_name}")
    @router.get("/api/models/{model_name}")
    @router.post("/v1/models/{model_name}")
    @router.post("/api/models/{model_name}")
    async def get_model(model_name: str) -> Dict[str, Any]:
        local = state.normalize_model_name(model_name)
        model_cfg = await state.resolve_model_config(local, allow_default=False)
        return {
            "id": local,
            "object": "model",
            "created": 0,
            "owned_by": "proxy",
            "root": model_cfg["name"],
            "permission": [],
        }

    @router.get("/api/tags")
    async def list_tags() -> Dict[str, Any]:
        discovery_errors = await state.ensure_discoverable_models_loaded()
        if not state.model_registry and discovery_errors:
            state.raise_discovery_error(discovery_errors[0])
        return {"models": build_tags_models(state.model_registry)}

    @router.get("/api/ps")
    async def ps_models() -> Dict[str, Any]:
        discovery_errors = await state.ensure_discoverable_models_loaded()
        if not state.model_registry and discovery_errors:
            state.raise_discovery_error(discovery_errors[0])
        return {"models": build_ps_models(state.model_registry)}

    @router.post("/api/show")
    async def show_model(request: Request) -> Dict[str, Any]:
        body = await parse_request_json(request, logger, allow_empty=True)
        model_name = state.normalize_model_name(body.get("model") or body.get("name") or state.default_model)
        model_cfg = await state.resolve_model_config(model_name, allow_default=False)
        source_cfg = state.resolve_source_config(model_cfg["source"])
        logger.info("show resolved_model=%s request_keys=%s", model_name, sorted(body.keys()))
        meta = model_cfg["meta"]
        family = meta.get("family", guess_model_family(model_name))
        tagged_name = f"{model_name}:latest"
        template = (
            "{{ if .System }}<|im_start|>system\\n{{ .System }}<|im_end|>\\n{{ end }}"
            "{{ if .Prompt }}<|im_start|>user\\n{{ .Prompt }}<|im_end|>\\n<|im_start|>assistant\\n{{ end }}"
            "{{ if .Response }}{{ .Response }}<|im_end|>\\n{{ end }}"
        )
        return {
            "model": tagged_name,
            "modified_at": now_iso(),
            "license": "",
            "system": "",
            "messages": [],
            "modelfile": (
                f'# Modelfile generated by "ollama show"\\n'
                f"# To build a new Modelfile based on this one, replace the FROM line with:\\n"
                f"# FROM {tagged_name}\\n"
                f"FROM {tagged_name}\\n"
                f'TEMPLATE """{ template }"""\\n'
                "PARAMETER stop \"<|im_start|>\"\\n"
                "PARAMETER stop \"<|im_end|>\"\\n"
            ),
            "parameters": (
                "stop                           \"<|im_start|>\"\\n"
                "stop                           \"<|im_end|>\"\\n"
            ),
            "template": template,
            "details": {
                "parent_model": "",
                "format": "gguf",
                "family": family,
                "families": [family],
                "parameter_size": meta.get("parameter_size", "7B"),
                "quantization_level": meta.get("quantization_level", "Q4_K_M"),
            },
            "model_info": {
                **merged_model_info(meta, family),
            },
            "capabilities": effective_capabilities(meta, source_cfg),
        }

    return router
